"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Custom tool definitions
@tool
def check_return_eligibility(purchase_date: str, item_category: str, order_id: str) -> dict:
    try:
        purchase_dt = datetime.strptime(purchase_date, '%Y-%m-%d')
        days_since_purchase = (datetime.now() - purchase_dt).days
        
        # Define return windows by category
        return_windows = {
            'electronics': 90,
            'clothing': 30,
            'books': 30,
            'home': 30,
            'toys': 30,
            'default': 30
        }
        
        # Non-returnable categories
        non_returnable = ['perishables', 'digital', 'gift_cards', 'personalized']
        
        category_lower = item_category.lower()
        
        if category_lower in non_returnable:
            return {
                'eligible': False,
                'reason': f'{item_category} items are not eligible for return',
                'order_id': order_id,
                'days_since_purchase': days_since_purchase
            }
        
        window = return_windows.get(category_lower, return_windows['default'])
        
        if days_since_purchase <= window:
            return {
                'eligible': True,
                'reason': f'Item is within {window}-day return window',
                'order_id': order_id,
                'days_since_purchase': days_since_purchase,
                'days_remaining': window - days_since_purchase
            }
        else:
            return {
                'eligible': False,
                'reason': f'Return window of {window} days has expired',
                'order_id': order_id,
                'days_since_purchase': days_since_purchase
            }
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Please use YYYY-MM-DD',
            'order_id': order_id
        }

@tool
def calculate_refund_amount(original_price: float, item_condition: str, return_reason: str) -> dict:
    condition_lower = item_condition.lower()
    reason_lower = return_reason.lower()
    
    refund_percentage = 100
    restocking_fee = 0
    shipping_refund = True
    
    # Defective or wrong item - full refund
    if reason_lower in ['defective', 'wrong_item']:
        refund_percentage = 100
        restocking_fee = 0
        shipping_refund = True
    # Changed mind - depends on condition
    else:
        if condition_lower == 'unopened':
            refund_percentage = 100
            restocking_fee = 0
        elif condition_lower == 'opened_unused':
            refund_percentage = 100
            restocking_fee = original_price * 0.15  # 15% restocking fee
        elif condition_lower == 'used':
            refund_percentage = 80
            restocking_fee = original_price * 0.20  # 20% restocking fee
        elif condition_lower == 'damaged':
            refund_percentage = 50
            restocking_fee = 0
        else:
            refund_percentage = 100
            restocking_fee = 0
        
        shipping_refund = False
    
    refund_amount = (original_price * refund_percentage / 100) - restocking_fee
    refund_amount = max(0, refund_amount)  # Ensure non-negative
    
    return {
        'original_price': original_price,
        'refund_amount': round(refund_amount, 2),
        'refund_percentage': refund_percentage,
        'restocking_fee': round(restocking_fee, 2),
        'shipping_refunded': shipping_refund,
        'item_condition': item_condition,
        'return_reason': return_reason
    }

@tool
def format_policy_response(policy_text: str, category: str = 'general') -> str:
    formatted = f"📋 Return Policy Information ({category.title()})\n"
    formatted += "=" * 50 + "\n\n"
    
    # Split into sections if possible
    sections = policy_text.split('\n\n')
    
    for i, section in enumerate(sections, 1):
        if section.strip():
            # Check if it's a header (short line, no punctuation at end)
            if len(section) < 60 and not section.strip().endswith('.'):
                formatted += f"\n📌 {section.strip()}\n"
                formatted += "-" * 40 + "\n"
            else:
                # Format as bullet points if multiple sentences
                sentences = [s.strip() for s in section.split('.') if s.strip()]
                if len(sentences) > 1:
                    for sentence in sentences:
                        if sentence:
                            formatted += f"  • {sentence}.\n"
                else:
                    formatted += f"  {section.strip()}\n"
            formatted += "\n"
    
    formatted += "\n" + "=" * 50 + "\n"
    formatted += "💡 Tip: Contact customer service for specific questions about your order.\n"
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
