"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime
from src.agents.policy_engine import get_policy_engine
from src.agents.decision_logger import get_decision_logger

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

You are using a configurable policy system. Use get_policy_info() to see the current policy version.

When using the retrieve tool for knowledge base queries, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Initialize policy engine (lazy loaded)
def _get_policy():
    """Get policy engine instance"""
    return get_policy_engine()

# Custom tool definitions
@tool
def check_return_eligibility(purchase_date: str, item_category: str, order_id: str) -> dict:
    """
    Check if an item is eligible for return based on purchase date and category.
    Uses configurable policy from YAML/JSON file.
    """
    try:
        policy = _get_policy()
        result = policy.check_eligibility(purchase_date, item_category)
        
        # Add order_id to result
        result['order_id'] = order_id
        
        # Log the decision
        try:
            decision_logger = get_decision_logger()
            decision_logger.log_eligibility_decision(
                order_id=order_id,
                purchase_date=purchase_date,
                category=item_category,
                eligible=result['eligible'],
                reason=result['reason'],
                policy_version=result.get('policy_version', 'unknown'),
                actor_id=ACTOR_ID,
                session_id=SESSION_ID
            )
        except Exception as log_error:
            print(f"Warning: Failed to log decision: {log_error}")
        
        return result
        
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Please use YYYY-MM-DD',
            'order_id': order_id
        }

@tool
def calculate_refund_amount(original_price: float, item_condition: str, return_reason: str) -> dict:
    """
    Calculate refund amount based on price, condition, and return reason.
    Uses configurable policy from YAML/JSON file.
    """
    try:
        policy = _get_policy()
        result = policy.calculate_refund(original_price, item_condition, return_reason)
        
        # Log the decision
        try:
            decision_logger = get_decision_logger()
            decision_logger.log_refund_decision(
                order_id='unknown',
                original_price=original_price,
                refund_amount=result['refund_amount'],
                item_condition=item_condition,
                return_reason=return_reason,
                policy_version=result.get('policy_version', 'unknown'),
                actor_id=ACTOR_ID,
                session_id=SESSION_ID
            )
        except Exception as log_error:
            print(f"Warning: Failed to log decision: {log_error}")
        
        return result
    except Exception as e:
        return {
            'error': f'Error calculating refund: {str(e)}',
            'original_price': original_price,
            'item_condition': item_condition,
            'return_reason': return_reason
        }

@tool
def get_policy_info() -> dict:
    """Get information about the current return policy in use"""
    try:
        policy = _get_policy()
        return policy.get_policy_info()
    except Exception as e:
        return {'error': str(e)}

@tool
def format_policy_response(policy_text: str, category: str = 'general') -> str:
    formatted = f"📋 Return Policy Information ({category.title()})\n"
    formatted += "=" * 50 + "\n\n"
    
    # Split into sections if possible
    sections = policy_text.split('\n\n')
    
    for i, section in enumerate(sections, 1):
        if section.strip():
            # Check if it's a header (short line, no punctuation at end)
            if len(section) < 60 and not section.strip().endswith('.'):
                formatted += f"\n📌 {section.strip()}\n"
                formatted += "-" * 40 + "\n"
            else:
                # Format as bullet points if multiple sentences
                sentences = [s.strip() for s in section.split('.') if s.strip()]
                if len(sentences) > 1:
                    for sentence in sentences:
                        if sentence:
                            formatted += f"  • {sentence}.\n"
                else:
                    formatted += f"  {section.strip()}\n"
            formatted += "\n"
    
    formatted += "\n" + "=" * 50 + "\n"
    formatted += "💡 Tip: Contact customer service for specific questions about your order.\n"
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list - includes policy-driven tools
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, get_policy_info, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
